### ISSUE TITLE
Missing support for git worktree

### ISSUE THREAD

**Issue by RalfJung** [rustyhorde/vergen#13]
I am getting the following error trying to use vergen 2.1.1:
```
error: failed to run custom build command for `miri v0.1.0 (/home/r/src/rust/miri.2)`                                                                                                                              
process didn't exit successfully: `/home/r/src/rust/miri.2/target/debug/build/miri-88c826e4cdc20f81/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-env=PROFILE=debug
cargo:rerun-if-changed=build.rs
cargo:rerun-if-changed=.git/HEAD

--- stderr
thread 'main' panicked at 'Unable to generate vergen constants!: Error(Io(Os { code: 20, kind: Other, message: "Not a directory" }), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', libcore/result.rs:1009:5
```
My `build.rs`:
```rust
extern crate vergen;

use std::env;

fn main() {
    // Forward the profile to the main compilation
    println!("cargo:rustc-env=PROFILE={}", env::var("PROFILE").unwrap());
    // Don't rebuild miri even if nothing changed
    println!("cargo:rerun-if-changed=build.rs");
    // vergen
    vergen().expect("Unable to generate vergen constants!");
}

fn vergen() -> vergen::Result<()> {
    use vergen::{ConstantsFlags, Vergen};

    let vergen = Vergen::new(ConstantsFlags::all())?;

    for (k, v) in vergen.build_info() {
        println!("cargo:rustc-env={}={}", k.name(), v);
    }

    Ok(())
}
```

**Comment by RalfJung** [comment]
Same with v3.0.1. Stacktrace:
```
stack backtrace:
   0:     0x5557e34a8125 - backtrace::backtrace::libunwind::trace::h73a7cad61c0d7e3b
                        at /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace::hc5b6f2ddf8a44c25
                        at /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/backtrace/mod.rs:42
   1:     0x5557e34a1f9e - backtrace::capture::Backtrace::new_unresolved::h1c811c9765d3735f
                        at /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.9/src/capture.rs:88
   2:     0x5557e34a099e - failure::backtrace::internal::InternalBacktrace::new::h780fb909f4761e02
                        at /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.2/src/backtrace/internal.rs:44
   3:     0x5557e349ff2c - failure::backtrace::Backtrace::new::h6a36df54d1b43814
                        at /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.2/src/backtrace/mod.rs:111
   4:     0x5557e348948d - <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from::hfde5c867c9746476
                        at /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.2/src/error/error_impl.rs:20
   5:     0x5557e34762be - <failure::error::Error as core::convert::From<F>>::from::hec28104e8d7a53b8
                        at /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.2/src/error/mod.rs:36
   6:     0x5557e3476b0c - vergen::output::envvar::generate_cargo_keys::hac67bdf905151ac8
                        at /home/r/.cargo/registry/src/github.com-1ecc6299db9ec823/vergen-3.0.1/src/output/envvar.rs:46
   7:     0x5557e3473951 - build_script_build::main::h30fd1225692138ac
                        at /home/r/src/rust/miri.2/build.rs:11
   8:     0x5557e347401f - std::rt::lang_start::{{closure}}::hb8736f9606989d28
                        at libstd/rt.rs:74
   9:     0x5557e34ee5b2 - std::rt::lang_start_internal::{{closure}}::h444bf05eb286eca1
                        at libstd/rt.rs:59
                         - std::panicking::try::do_call::hb527d54965a8815a
                        at libstd/panicking.rs:310
  10:     0x5557e35004a9 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  11:     0x5557e34e28e5 - std::panicking::try::h83b5294aab121d1a
                        at libstd/panicking.rs:289
                         - std::panic::catch_unwind::h15c1ea783c7910d5
                        at libstd/panic.rs:392
                         - std::rt::lang_start_internal::hcc3e9196a926118d
                        at libstd/rt.rs:58
  12:     0x5557e3473ff7 - std::rt::lang_start::h0c6d8b878c9eadb4
                        at libstd/rt.rs:74
  13:     0x5557e34739c9 - main
  14:     0x7f42adac1b16 - __libc_start_main
  15:     0x5557e3473739 - _start
  16:                0x0 - <unknown>', libcore/result.rs:1009:5
```

**Comment by RalfJung** [comment]
This problem is caused by me using a git worktree. In that case, there is no `.git` directory, there is just a `.git` file saying
```
gitdir: /home/r/src/rust/miri/.git/worktrees/miri.2
```

**Comment by CraZySacX** [comment]
Never heard of a git worktree.  I'll look into it.

**Comment by CraZySacX** [comment]
So it looks like the .git file (if worktrees are enabled) contains the path to the private git directory that contains the actual information we are looking for.  I'll have to setup a test repository to see how this works exactly, but I don't think it'll be too hard to add support.

**Comment by CraZySacX** [comment]
Added with 3.0.2.   Tested locally with a worktree and seemed to work as intended.

If the `HEAD` file, located at `<full path to regular .git directory>/worktrees/<work-tree-name>` changes, build is re-run.

If the file that `HEAD` points at, located at `<full path to regular .git directory>/<contents of HEAD>` changes, the build is re-run.

Verified with `cargo -vv`

**Comment by CraZySacX** [comment]
Currently working on backport, should have this done soon.

**Comment by CraZySacX** [comment]
Added 2.1.2.   And I used a worktree to get it done.   I'm glad you introduced me to this feature in git I had no idea about :).

**Comment by RalfJung** [comment]
This seem to work, thanks a lot :)

And yes, worktrees are super awesome. I have tons of them by now.
