### ISSUE TITLE
feature::git::test::git_describe_works on tagged commit fails

### ISSUE THREAD

**Issue by heftig** [rustyhorde/vergen#42]
When running the test suite on 862f1e8aba9ccb5df275f5d242cc1246f6341fae (tagged `4.0.1`), it fails:

```
---- feature::git::test::git_describe_works stdout ----
thread 'feature::git::test::git_describe_works' panicked at 'assertion failed: config.cfg_map().get(&VergenKey::Semver).map(|x|\n                                                 x.as_ref().unwrap().to_string())\n    != env::var(\"CARGO_PKG_VERSION\").ok()', src/feature/git.rs:233:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:50:5
   3: vergen::feature::git::test::git_describe_works
             at ./src/feature/git.rs:233:9
   4: vergen::feature::git::test::git_describe_works::{{closure}}
             at ./src/feature/git.rs:228:5
   5: core::ops::function::FnOnce::call_once
             at /home/jan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/ops/function.rs:227:5
```

Applying this patch gives some more detail:

```diff
diff --git i/src/feature/git.rs w/src/feature/git.rs
index 7a4a05f..065f569 100644
--- i/src/feature/git.rs
+++ w/src/feature/git.rs
@@ -230,12 +230,12 @@ mod test {
         let tags_path = PathBuf::from("testdata").join("tagsrepo");
         add_git_config(ConstantsFlags::all(), Some(tags_path), &mut config)?;
         check_git_keys(config.cfg_map());
-        assert!(
+        assert_ne!(
             config
                 .cfg_map()
                 .get(&VergenKey::Semver)
-                .map(|x| x.as_ref().unwrap().to_string())
-                != env::var("CARGO_PKG_VERSION").ok()
+                .map(|x| x.as_ref().unwrap().to_string()),
+            env::var("CARGO_PKG_VERSION").ok(),
         );
         check_git_instructions(config.cfg_map());
         assert!(config.ref_path().is_some());
```
```
---- feature::git::test::git_describe_works stdout ----
thread 'feature::git::test::git_describe_works' panicked at 'assertion failed: `(left != right)`
  left: `Some("4.0.1")`,
 right: `Some("4.0.1")`', src/feature/git.rs:233:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: vergen::feature::git::test::git_describe_works
             at ./src/feature/git.rs:233:9
   3: vergen::feature::git::test::git_describe_works::{{closure}}
             at ./src/feature/git.rs:228:5
   4: core::ops::function::FnOnce::call_once
             at /home/jan/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
   5: core::ops::function::FnOnce::call_once
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/ops/function.rs:227:5
```

**Comment by CraZySacX** [comment]
Try running `git submodule update --init` on the base and running these again.   I added some test repos as submodules to the `testdata` directory specifically to test more git scenarios.   Let me know if that doesn't work as I'm not able to reproduce this.

I'll updated the docs with a CONTRIBUTING.md guide so this is more clear.

**Comment by heftig** [comment]
Ah, right, thanks. I missed those. Maybe the tests should make sure the submodules are checked out.
